version: '3.8'

services:
  mi_mysql:
    image: mysql:latest
    ports:
      - "3036:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  backend:
    context: ./src
    depends_on:
      - mi_mysql
